### ISSUE TITLE
mcufriend_special.h set does not work in stm32duino core ver 1.9

### ISSUE THREAD

**Issue by clear-sky** [prenticedavid/MCUFRIEND_kbv#136]
hi dear david thanks for your help for running my lcd with ili9486 due this issue 
https://github.com/prenticedavid/MCUFRIEND_kbv/issues/114
my mcu is stm32f103re and everything was good in ver 1.8 stm32duino
but this trick does not work in version 1.9 stm32duino and give tons of errors please see first lines of this errors:
In file included from /home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/MCUFRIEND_kbv.cpp:35,
                 from /home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/OPENSMART_kbv.cpp:20:
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:782:2: error: #error unsupported STM32
  782 | #error unsupported STM32
      |  ^~~~~
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:952:2: error: #error REGS group
  952 | #error REGS group
      |  ^~~~~
In file included from /home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/MCUFRIEND_kbv.cpp:35:
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:782:2: error: #error unsupported STM32
  782 | #error unsupported STM32
      |  ^~~~~
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:952:2: error: #error REGS group
  952 | #error REGS group
      |  ^~~~~
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/MCUFRIEND_kbv.cpp: In function 'void write24(uint16_t)':
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:959:25: error: 'write_8' was not declared in this scope; did you mean 'write8'?
  959 | #define write8(x)     { write_8(x); WRITE_DELAY; WR_STROBE; IDLE_DELAY; }
      |                         ^~~~~~~
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/MCUFRIEND_kbv.cpp:84:5: note: in expansion of macro 'write8'
   84 |     write8(r);
      |     ^~~~~~
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/MCUFRIEND_kbv.cpp: In function 'void write24(uint16_t)':
/home/conrad/Arduino/libraries/MCUFRIEND_kbv-master/utility/mcufriend_shield.h:959:25: error: 'write_8' was not declared in this scope; did you mean 'write8'?
  959 | #define write8(x)     { write_8(x); WRITE_DELAY; WR_STROBE; IDLE_DELAY; }

**Comment by clear-sky** [comment]
Add #define USE_CLEAR_SKY and this block to mcufriend_special.h
Add USE_SPECIAL to mcufriend_shield.h

//############################### CLEAR_SKY GENERIC_F103RET6 or MAPLE_RET6 ###########################################
#elif defined(USE_CLEAR_SKY) && (defined(ARDUINO_GENERIC_F103RET6) || defined(ARDUINO_MAPLE_RET6))
#warning USE_CLEAR_SKY on GENERIC_F103RET6 or MAPLE_RET6

//LCD pins  |D7 |D6 |D5 |D4 |D3 |D2 |D1 |D0 | |RD |WR |RS  |CS  |RST | |SD_SS|SD_DI|SD_DO|SD_SCK|
//STM32 pin |PC7|PC6|PC5|PC4|PC3|PC2|PC1|PC0| |PC8|PC9|PC11|PC10|PC12| 

#if defined(ARDUINO_ARCH_STM32)   //regular CMSIS libraries
#define REGS(x) x
#define GPIO_INIT()   { RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN | RCC_APB2ENR_IOPDEN | RCC_APB2ENR_AFIOEN; \
        AFIO->MAPR |= AFIO_MAPR_SWJ_CFG_1;}
#else                                                                  //weird Maple libraries
#define REGS(x) regs->x
#endif

#define WRITE_DELAY { }
#define READ_DELAY  { RD_ACTIVE; }
#define GROUP_MODE(port, reg, mask, val)  {port->REGS(reg) = (port->REGS(reg) & ~(mask)) | ((mask)&(val)); }
#define GP_OUT(port, reg, mask)           GROUP_MODE(port, reg, mask, 0x33333333)
#define GP_INP(port, reg, mask)           GROUP_MODE(port, reg, mask, 0x44444444)
#define PIN_OUTPUT(port, pin) {\
        if (pin < 8) {GP_OUT(port, CRL, 0xF<<((pin)<<2));} \
        else {GP_OUT(port, CRH, 0xF<<((pin&7)<<2));} \
    }
#define PIN_INPUT(port, pin) { \
        if (pin < 8) { GP_INP(port, CRL, 0xF<<((pin)<<2)); } \
        else { GP_INP(port, CRH, 0xF<<((pin&7)<<2)); } \
    }
#define PIN_HIGH(port, pin)   (port)-> REGS(BSRR) = (1<<(pin))
#define PIN_LOW(port, pin)    (port)-> REGS(BSRR) = (1<<((pin)+16))

#define RD_PORT GPIOC
#define RD_PIN  8
#define WR_PORT GPIOC
#define WR_PIN  9
#define CD_PORT GPIOC
#define CD_PIN  11
#define CS_PORT GPIOC
#define CS_PIN  10
#define RESET_PORT GPIOC
#define RESET_PIN  12

// configure macros for the data pins
#define write_8(d)    { GPIOC->REGS(BSRR) = 0x00FF << 16; GPIOC->REGS(BSRR) = (d) & 0xFF; }
#define read_8()      (GPIOC->REGS(IDR) & 0xFF)
//                                         PC7 ..PC0
#define setWriteDir() {GP_OUT(GPIOC, CRL, 0xFFFFFFFF); }
#define setReadDir()  {GP_INP(GPIOC, CRL, 0xFFFFFFFF); }

#define write8(x)     { write_8(x); WRITE_DELAY; WR_STROBE; }
#define write16(x)    { uint8_t h = (x)>>8, l = x; write8(h); write8(l); }
#define READ_8(dst)   { RD_STROBE; READ_DELAY; dst = read_8(); RD_IDLE; }
#define READ_16(dst)  { uint8_t hi; READ_8(hi); READ_8(dst); dst |= (hi << 8); }

changed ARDUINO_GENERIC_F103RET6 and GENERIC_F103RET6 to
ARDUINO_GENERIC_F103RE and GENERIC_F103RE
problem solved
thank you dear david
